### PR TITLE
Issue 2

### LINKED ISSUE #2: Support hashes
We should support [hashes](http://jakegoulding.com/blog/2013/01/15/a-little-dip-into-rubys-marshal-format/).

<hr/>
[JRuby](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/runtime/marshal/UnmarshalStream.java#L214-L216)

### PR DESCRIPTION
**Pull request by filib**
This PR adds support for parsing Hashes.

Closes #2.

### CODE REVIEW

**Comment by adinapoli** [comment]
:tada:

**Comment by filib** [comment]
It was your comment on the other issue that nudged me into doing this. Thanks man!

**Comment by adinapoli** [comment]
Good to hear. I think it's part of the "game". Having more interaction might snowball into something useful. Too many of my projects just dies for luck of motivation!

**Comment by filib** [comment]
I think you're right. I could have spent a few days trying to further "beautify" things but your interaction prompted me into, "fuck, I better actually do something useful."

**Comment by adinapoli** [comment]
Perfection never ships, they say.

**Pull request merged**
